apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sNoRunAsRoot
metadata:
  name: no-run-as-root
spec:
  enforcementAction: deny
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
      - apiGroups: ["apps"]
        kinds: ["Deployment"]
    excludedNamespaces:
      - kube-system
      - gatekeeper-system
